version: v0.3.0

listeners:
  - type: agent
    name: network_assistant
    address: 0.0.0.0
    port: 10000
    router: plano_orchestrator_v1
    agents:
      - id: app_server
        description: Handles network device operations and information extraction.

  - type: model
    name: model_gateway
    address: 0.0.0.0
    port: 12000

# Centralized way to manage LLMs, manage keys, retry logic, failover and limits in a central way
model_providers:
  - access_key: $OPENAI_API_KEY
    model: openai/gpt-4o
    default: true

agents:
  - id: app_server
    url: http://127.0.0.1:80
